Add local id support
retailnext/api2go pull request #2
Opened 2020-10-09 11:14 UTC by IvanRN

Upcoming version of the JSONAPI (1.1) has a local id feature. Local
id or lid is a object identifier is used when id is missing along
with a type of the object.

2020-10-09 12:29 UTC, artlo requested changes

2020-10-09 12:29 UTC, artlo commented on jsonapi/unmarshal.go
> +		castedTarget, _ = castedTargetWithLid.(UnmarshalIdentifier)
I guess it's not needed, because taget is Pointer otherwise ID will be lost in line 190

2020-10-09 12:29 UTC, artlo commented on jsonapi/unmarshal.go
> +				err = castedToOne.SetToOneReferenceID(name, rel.Data.DataObject.LID)
I guess that is not correct to set LID to reference ID. Let's create the another interface with function `SetToOneReferenceIDWithLID`

2020-10-09 12:29 UTC, artlo commented on jsonapi/unmarshal.go
> +				err = castedToOne.SetToOneReferenceID(name, rel.Data.DataObject.ID)
What is about SetMultipleReferences?

2020-10-16 13:47 UTC, IvanRN commented
deleting since we decided to try different approach

2020-10-16 13:47 UTC, closed without merging